server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql:///pdn_shop
    password: 123
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.mchange.v2.c3p0.ComboPooledDataSource
  data:
    solr:
      host: http://192.168.72.172:8080/solr
mybatis:
  mapper-locations: classpath*:com/qf/shop/dao/mapper/*.xml
  type-aliases-package: com.qf.entity
dubbo:
  application:
    name: server_provider
  registry:
    address: zookeeper://192.168.72.172:2181
  protocol:
    name: dubbo
    port: 20880